apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-nginx
  namespace: test-argo   # Argo CD app namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-nginx
  template:
    metadata:
      labels:
        app: canary-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 15s}
      - setWeight: 50
      - pause: {duration: 15s}
      - setWeight: 100
      - pause: {duration: 10s}
      analysis:
        templates:
        - templateName: success-rate
          args:
          - name: serviceName
            value: canary-nginx
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: test-argo
spec:
  metrics:
  - name: http-success-rate
    interval: 10s
    successCondition: result >= 95
    failureCondition: result < 95
    provider:
      prometheus:
        query: sum(rate(http_requests_total{service="{{args.serviceName}}"}[1m])) 
