apiVersion: v1
kind: Service
metadata:
  name: my-app-active
  namespace: test-argo
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-preview
  namespace: test-argo
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
